### ISSUE TITLE
MoskitoUIFilter / VersionUtil should not imply that /WEB-INF/lib and /META-INF exist

### ISSUE THREAD

**Issue by FelixJongleur42** [anotheria/moskito#116]
Servlet Container with no \WEB-INF\lib or no \META-INF\ produces this.
Source code already states "this is pretty hacky now"
see http://fossies.org/dox/moskito-moskito-2.7.6/VersionUtil_8java_source.html

```
2016-08-08 10:22:51,351 ERROR [main] webui.MoskitoUIFilter:49 init(org.eclipse.jetty.servlet.FilterHolder$Config@75d1477a)
java.lang.IllegalArgumentException: Directory <path-to>\WEB-INF\lib doesn't exists.
	at net.anotheria.util.maven.MavenVersionReader.findJarInDirectory(MavenVersionReader.java:120)
	at net.anotheria.moskito.webui.util.VersionUtil.getWebappLibVersion(VersionUtil.java:24)
	at net.anotheria.moskito.webui.MoskitoUIFilter.init(MoskitoUIFilter.java:41)
```

**Comment by dvayanu** [comment]
Hi Felix,
just out of interest, do you use standalone jetty or embedded in your IDE?

**Comment by FelixJongleur42** [comment]
the latter

**Comment by dvayanu** [comment]
so is this something that means that it "doesn't work for you" or "just annoying log spam"? Because obviously in embedded environment its not possible to determine the version (neither its needed, since you know it anyway)

**Comment by FelixJongleur42** [comment]
It's irritating when the log gets spammed with the full stack trace.
