### ISSUE TITLE
Problem with moskito-javaagent-lite-1.0.0 in tomcat7

### ISSUE THREAD

**Issue by gdxmabat** [anotheria/moskito#133]
Hi there !! 

I am using moskito-javaagent-lite-1.0.0 in my JSF2, tomcat7 and JDK 7 java web application. 

I just configure moskito-javaagent-lite-1.0.0 in tomcat startup and include dependencies 

<dependency>
		  <groupId>net.anotheria</groupId>
		  <artifactId>moskito-inspect-remote</artifactId>
		  <version>${moskito.version}</version>
</dependency>

But when i start tomcat, i got the next error: 

GRAVE: Error configurando escuchador de aplicación de clase net.anotheria.moskito.web.session.SessionCountProducer
java.lang.ExceptionInInitializerError
	at net.anotheria.moskito.core.registry.ProducerRegistryFactory.init(ProducerRegistryFactory.java:70)
	at net.anotheria.moskito.core.registry.ProducerRegistryFactory.<clinit>(ProducerRegistryFactory.java:54)
	at net.anotheria.moskito.web.session.SessionCountProducer.<init>(SessionCountProducer.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:114)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5015)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5615)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1571)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1561)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "50.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.parseLong(Long.java:483)
	at net.anotheria.moskito.core.threshold.ThresholdRepository.readConfig(ThresholdRepository.java:299)
	at net.anotheria.moskito.core.threshold.ThresholdRepository.<init>(ThresholdRepository.java:51)
	at net.anotheria.moskito.core.threshold.ThresholdRepository.<clinit>(ThresholdRepository.java:44)
	... 18 more

Where is the problem ???

Regards, Mario.

**Comment by sshscp** [comment]
Hello.
 AS far as a I can see - Your default system locale does not  use '.' as  floating point number separator - But in  default threashold configuration - '.' is  used... so  system falls down... 
There are  few possible options 
1)  change locale floating point separator ;
2) edit  pre-configured  values in scope of  configuration   
To Edit : In scope of moskito-inspect stand alone - there's configuration 'moskito.json' - there  You may  find  "@thresholdsConfig":  section, which   contains pre-configurations.... If You'll check it   - ther You'll find SystemCPULoad - configuration which provides  float point values  like "50.0"/"75.0"   etc...
Regards.

**Comment by dzhmud** [comment]
Isn't it just this case? https://jira.opensource.anotheria.net/projects/MSK/issues/MSK-339

**Comment by dvayanu** [comment]
Ist the problem resolved?
