### ISSUE TITLE
Can not start inspector from command line in 2.8.5

### ISSUE THREAD

**Issue by thhart** [anotheria/moskito#192]
I downloaded the standard distribution package and tried to start the inspector in a Linux environment. It starts somehow but the http connector service fails with a binding conflict as seen in catalina logs. I made sure no other services running on this port so I think it is a configuration problem in tomcat.
There is something listening on port 8088 after startup but connecting via http gives no valid responses then. 

```
% /opt/moskito/moskito-inspect/tomcat: bin/startup.sh
JAVA_OPTS: -Dsun.rmi.transport.tcp.handshakeTimeout=5000
Using CATALINA_BASE:   /opt/moskito/moskito-inspect/tomcat
Using CATALINA_HOME:   /opt/moskito/moskito-inspect/tomcat
Using CATALINA_TMPDIR: /opt/moskito/moskito-inspect/tomcat/temp
Using JRE_HOME:       /usr/lib/jvm/java-8-oracle
Using CLASSPATH:       /opt/moskito/moskito-inspect/tomcat/bin/bootstrap.jar:/opt/moskito/moskito-inspect/tomcat/bin/tomcat-juli.jar
Using CATALINA_PID:    moskito-inspect.pid
Tomcat started.
```

catalina.out
```
20-Mar-2018 03:57:38.536 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
20-Mar-2018 03:57:38.683 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8088"]
20-Mar-2018 03:57:38.693 SEVERE [main] org.apache.coyote.AbstractProtocol.init Failed to initialize end point associated with ProtocolHandler ["http-nio-8088"]
 java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
```

**Comment by thhart** [comment]
I found an other service running already. Sorry for the noise.

**Comment by dvayanu** [comment]
If only all issues would be self-resolving like this one ;-)
