### ISSUE TITLE
Issue associated with AWS EC2

### ISSUE THREAD

**Issue by maheshraju81** [anotheria/moskito#214]
I have my tomcat server inside an EC2 instance.  I configured moskito and the services is up and running in port 9401. However I am unable to connect to it from my local machine. I am using a windows machine and able to telnet to the port. The port is already opened in AWS security policy.

**Comment by dvayanu** [comment]
Is this port publicly available? If yes, you can the ip to support@moskito.org.
Also can you provide the config which you used for the monitored component (the one you connect too). 
Is there any error message or just connection refused.

**Comment by maheshraju81** [comment]
I am referring to this tutorial for the set up.

http://blog.anotheria.net/msk/the-complete-moskito-integration-guide-step-1/

The port is not publicly available.
Not using any specific configuration. Following the steps mentioned in the link.
Error message mentions connection timeout.

**Comment by dvayanu** [comment]
Can you connect from the same machine via telnet? Are you sure you are using port 9401 only for moskito communication and not for the http communication (sounds silly, but actually happened)?

**Comment by maheshraju81** [comment]
Yes i can connect the machine from telnet. 
Please find the netstat -tunlp from the machine.
![ss](https://user-images.githubusercontent.com/17562998/42986488-566f6898-8c13-11e8-89e9-d7a91a8fff1b.png)

**Comment by dvayanu** [comment]
ok, can you please provide the error page from the moskito-console (moskito-inspect) which you are using to connect. thank you

**Comment by maheshraju81** [comment]
Please find the error log from moskito-err.log

[http-apr-8080-exec-2] ERROR  net.anotheria.maf.MAFFilter:284 - Unexpected exception in processing
org.distributeme.core.exception.ServiceUnavailableException: Service unavailable due to rmi failure: Connection refused to host: ***.31.29.***; nested exception is: 
	java.net.ConnectException: Connection timed out: connect
	at net.anotheria.moskito.webui.shared.api.generated.RemoteAdditionalFunctionalityAPIStub.mapException(RemoteAdditionalFunctionalityAPIStub.java:1807) ~[moskito-webui-2.8.7.jar:2.8.7]
	at net.anotheria.moskito.webui.shared.api.generated.RemoteAdditionalFunctionalityAPIStub.getIntervalInfos(RemoteAdditionalFunctionalityAPIStub.java:771) ~[moskito-webui-2.8.7.jar:2.8.7]
	at net.anotheria.moskito.webui.shared.api.generated.RemoteAdditionalFunctionalityAPIStub.getIntervalInfos(RemoteAdditionalFunctionalityAPIStub.java:762) ~[moskito-webui-2.8.7.jar:2.8.7]
	at net.anotheria.moskito.webui.shared.api.generated.RemoteAdditionalFunctionalityAPIStub.getIntervalInfos(RemoteAdditionalFunctionalityAPIStub.java:638) ~[moskito-webui-2.8.7.jar:2.8.7]
	at net.anotheria.moskito.webui.shared.action.BaseMoskitoUIAction.preProcess(BaseMoskitoUIAction.java:485) ~[moskito-webui-2.8.7.jar:2.8.7]
	at net.anotheria.maf.MAFFilter.doPerform(MAFFilter.java:262) [ano-maf-2.2.0.jar:2.2.0]
	at net.anotheria.maf.MAFFilter.doFilter(MAFFilter.java:217) [ano-maf-2.2.0.jar:2.2.0]
	at net.anotheria.moskito.webui.MoskitoUIFilter.doFilter(MoskitoUIFilter.java:145) [moskito-webui-2.8.7.jar:2.8.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.59]
	at net.anotheria.anoplass.api.filter.APIFilter.doFilter(APIFilter.java:107) [ano-plass-2.1.1.jar:2.1.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.59]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.59]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.59]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.59]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [catalina.jar:7.0.59]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074) [tomcat-coyote.jar:7.0.59]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.59]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466) [tomcat-coyote.jar:7.0.59]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455) [tomcat-coyote.jar:7.0.59]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.59]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
**_Caused by: java.rmi.ConnectException: Connection refused to host: ***.31.29.***; nested exception is: 
	java.net.ConnectException: Connection timed out: connect_**
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[na:1.8.0_31]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216) ~[na:1.8.0_31]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202) ~[na:1.8.0_31]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130) ~[na:1.8.0_31]
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:194) ~[na:1.8.0_31]
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:148) ~[na:1.8.0_31]
	at com.sun.proxy.$Proxy21.getIntervalInfos(Unknown Source) ~[na:na]
	at net.anotheria.moskito.webui.shared.api.generated.RemoteAdditionalFunctionalityAPIStub.getIntervalInfos(RemoteAdditionalFunctionalityAPIStub.java:694) ~[moskito-webui-2.8.7.jar:2.8.7]
	... 27 common frames omitted
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_31]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[na:1.8.0_31]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_31]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_31]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_31]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_31]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_31]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_31]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_31]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_31]
	at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_31]
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40) ~[na:1.8.0_31]
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148) ~[na:1.8.0_31]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613) ~[na:1.8.0_31]
	... 34 common frames omitted

**Comment by maheshraju81** [comment]
Also I am able to connect to it when I deploy the  moskito war file in the same tomcat instance which I want to monitor. it gets connected by using localhost as host and 9401 as port.

**Comment by maheshraju81** [comment]
I am unable to see the services I annotated in the producers tab. Is this because both are in the same container?

**Comment by dvayanu** [comment]
no you should see the services as soon as you are connected AND there are requests to these service.
Could you check the /etc/hosts of your machine? It is possible that it resolves itself as 127.0.0.1 and then connection is not possible remotely.
You can mask real ip.
Example: 
correct config:
10.110.7.16     DE1THCLCMS01
127.0.0.1   localhost

wrong config (at least from rmi's point of view)
127.0.0.1   DE1THCLCMS01.local DE1THCLCMS01
10.110.7.16     DE1THCLCMS01

**Comment by maheshraju81** [comment]
Please find my /etc/hosts below

127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

**Comment by dvayanu** [comment]
what does your host resolve to? uname -a usually shows it on second position.
If you add your external address to the /etc/hosts with this name, it should work (after restart).
Alternatively: you can add this option java.rmi.server.hostname to the monitored app's tomcat:
export JAVA_OPTS=$JAVA_OPTS -Djava.rmi.server.hostname=external_ip
it is described here:
https://docs.oracle.com/javase/7/docs/technotes/guides/rmi/javarmiproperties.html

**Comment by maheshraju81** [comment]
The last step setting hostname worked. 

But still I do not see my service under the Service in producers. I have annotated it and called the service multiple times. It seems like only moskito services are listed under it.

**Comment by dvayanu** [comment]
You has been following the guide, so you added aop to your maven build? can you check if there is a class in the WEB-INF/classes, same directory as your service with name YourService$AjcClosure1.class ?

**Comment by maheshraju81** [comment]
Yes the class is present. I am using a maven clean install to create the war file.

**Comment by maheshraju81** [comment]
The requests are made properly and I am getting a response. Its a POST request. 

The IP representation is correct.

using only @monitor in the class

import net.anotheria.moskito.aop.annotation.Monitor;
//rest of the imports

@RestController
@RequestMapping("/payment")
@Monitor(producerId = "PaymentService")
public class PaymentService {

//rest of the code.

**Comment by dvayanu** [comment]
Hi again, sorry for the weekend delay.
If its a POST request you should see it in the RequestURI part. Do you?

**Comment by maheshraju81** [comment]
Hurray!! It worked. Thanks a lot for the help. Planning to monitor a load test today. 

Got one suggestion the documentation looks confusing. I lost some time figuring out where to start and what to do.

**Comment by dvayanu** [comment]
glad it worked. I am closing the issue then. Please feel free to contact us anytime here or via email or onsite help. If you have concrete suggestions on how to make the documentation better we are very open to all suggestions!!!
