### ISSUE TITLE
Name of web-fragment in moskito-webui should be "MoSKitoWebUI"

### ISSUE THREAD

**Issue by frankbregulla1111** [anotheria/moskito#42]
With commit 141eff703b23ee0de310d64883fec516281694ee the name of the web-fragment.xml in moskito-webui was changed from "MoSKitoWebUI" to "MoSKitoInspectShared". However the ordering in web-fragment.xml in moskito-web references "MoSKitoWebUI". So one of the names should be changed to match the other.

This leads to the problem that moskito cannot be deployed in Jetty 8. Jetty will refuse to start with a "java.lang.IllegalStateException: Circular references for fragments" message.

Tomcat 7 however has no problem deploying this..

**Comment by FelixJongleur42** [comment]
Is there actually a solution without the workaround in the web.xml? I still see this when **not** using the _absolute-ordering_ tag. Shouldn't this be fixed by using _ordering_ in the corresponding web-fragment.xml?

```
java.lang.IllegalStateException: Circular references for fragments
        at org.eclipse.jetty.webapp.Ordering$RelativeOrdering.order(Ordering.java:208)
        at org.eclipse.jetty.webapp.MetaData.orderFragments(MetaData.java:365)
        at org.eclipse.jetty.webapp.MetaData.setOrdering(MetaData.java:533)
        at org.eclipse.jetty.webapp.MetaData.addFragment(MetaData.java:296)
        at org.eclipse.jetty.webapp.FragmentConfiguration.findWebFragments(FragmentConfiguration.java:75)
        at org.eclipse.jetty.webapp.FragmentConfiguration.preConfigure(FragmentConfiguration.java:44)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:468)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:504)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

```

**Comment by dvayanu** [comment]
Hi @FelixJongleur42 ,

so you are using standalone or embedded mode?
Because I am using mostly embedded myself and I don't see this problem.
Does it only happen in jetty?

**Comment by FelixJongleur42** [comment]
Yes and yes, I am using the workaround now.
