### ISSUE TITLE
Cannot start more than one webapp in tomcat with moskito-inspect-remote

### ISSUE THREAD

**Issue by Henning-B** [anotheria/moskito#74]
When starting more than one webapp with moskito-inspect-remote in the same tomcat, the tomcat fails to startup with the following log message:
INFO  2015-07-09 18:01:46,373 [localhost-startStop-1] org.distributeme.core.RegistryUtil - registrationIpMappingSet: 
INFO  2015-07-09 18:01:46,388 [localhost-startStop-1] org.distributeme.support.eventservice.generated.EventServiceRMIBridgeServer - Getting local registry
INFO  2015-07-09 18:01:46,388 [localhost-startStop-1] org.distributeme.core.RMIRegistryUtil - Creating local registry
INFO  2015-07-09 18:01:46,389 [localhost-startStop-1] org.distributeme.core.RMIRegistryUtil - Tying to bind to 9101
ERROR 2015-07-09 18:01:46,395 [localhost-startStop-1] org.distributeme.core.RMIRegistryUtil - local rmi registry port specified but not useable
java.rmi.server.ExportException: internal error: ObjID already in use
	at sun.rmi.transport.ObjectTable.putTarget(ObjectTable.java:186) ~[na:1.7.0_79]
	at sun.rmi.transport.Transport.exportObject(Transport.java:105) ~[na:1.7.0_79]
	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:259) ~[na:1.7.0_79]
	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411) ~[na:1.7.0_79]
	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147) ~[na:1.7.0_79]
	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:207) ~[na:1.7.0_79]
	at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:122) ~[na:1.7.0_79]
	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:108) ~[na:1.7.0_79]
	at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:203) ~[na:1.7.0_79]
	at org.distributeme.core.RMIRegistryUtil.findOrCreateRegistry(RMIRegistryUtil.java:58) ~[distributeme-core-2.2.1.jar:2.2.1]
	at org.distributeme.support.eventservice.generated.EventServiceRMIBridgeServer.createServiceAndRegisterLocally(EventServiceRMIBridgeServer.java:88) [distributeme-support-2.2.1.jar:2.2.1]
	at org.distributeme.support.eventservice.DiMeRemoteEventChannelRMISupport.initEventService(DiMeRemoteEventChannelRMISupport.java:205) [distributeme-support-2.2.1.jar:2.2.1]
...

**Comment by dvayanu** [comment]
This is fixed in https://jira.opensource.anotheria.net/browse/MSK-324 - 2.7.4
